### ISSUE TITLE
collision on created property

### ISSUE THREAD

**Issue by korostelevm** [cyclic-software/db-sdk#1]
when trying to updated `created`

```
  ValidationException: Invalid UpdateExpression: Two document paths overlap with each other; must remove or rewrite one of these paths; path one: [created], path two: [created]

      at deserializeAws_json1_0UpdateItemCommandError (cyclic-common/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2677:24)
      at cyclic-common/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at cyclic-common/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
      at StandardRetryStrategy.retry (cyclic-common/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
      at cyclic-common/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
      at cyclic-common/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/UpdateCommand.js:37:26
          at async Promise.all (index 0)
      at upsert (cyclic-common/node_modules/cyclic-dynamodb/src/cy_db_item.js:85:19)
          at async Promise.all (index 0)
```

**Comment by NurTasin** [comment]
I am also facing this issue. Aren't there any fix for this issue?
