### ISSUE TITLE
context.endpoint is not a function

### ISSUE THREAD

**Issue by samirp91** [cyclic-software/db-sdk#31]
When following the documentation to connect to the DB locally and get or set a value, I am getting the following error:

```
node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:6534
    const { hostname, protocol = "https", port, path: basePath } = await context.endpoint();
                                                                                 ^

TypeError: context.endpoint is not a function
    at buildHttpRpcRequest (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:6534:82)
    at serializeAws_json1_0UpdateItemCommand (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:477:12)
    at serialize (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/UpdateItemCommand.js:30:72)
    at /Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:27
    at /Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@cyclic.sh/dynamodb/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:32
    at /Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/UpdateCommand.js:37:32
    at DynamoDBDocumentClient.send (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@aws-sdk/smithy-client/dist-cjs/client.js:20:20)
    at upsert (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@cyclic.sh/dynamodb/dist/cy_db_item.js:81:19)
    at CyclicItem.set (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@cyclic.sh/dynamodb/dist/cy_db_item.js:267:13)
    at CyclicCollection.set (/Users/samir/Projects/kapswim/kapswim-email-backend/node_modules/@cyclic.sh/dynamodb/dist/cy_db_collection.js:44:19)

Node.js v20.3.1
```

This is happening with version 0.0.34. It is working with 0.0.33

**Comment by seekayel** [comment]
@samirp91 apologies, I thought I responded. I am not able to reproduce when I run with v0.0.35 using this code:

https://github.com/cyclic-software/dynamodb#example

Are you still seeing this error?

**Comment by samirp91** [comment]
I haven't updated my code since I created this issue. My code is working fine so I'm gonna leave it as is for now.
